# Generated by Django 4.2.5 on 2023-10-10 14:11

import color_city_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('removed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_num', models.CharField(max_length=15)),
                ('discount_rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('user_role', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('removed', models.BooleanField(blank=True, default=False, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='color_city_api.branch')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('item_number', models.CharField(default=color_city_api.models.generate_product_number, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('total_quantity', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.IntegerField()),
                ('package', models.CharField(choices=[('L', 'Liter'), ('PC', 'Piece'), ('PCS', 'Pieces'), ('GL', 'Gallons')], default='GL', max_length=255)),
                ('item_price_w_vat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_price_wo_vat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('catalyst', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('removed', models.BooleanField(blank=True, default=False, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='color_city_api.brand')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='color_city_api.supplier'),
        ),
    ]
