# Generated by Django 4.2.5 on 2023-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_rate',
            field=models.IntegerField(),
        ),
    ]
