# Generated by Django 4.2.5 on 2023-10-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0002_alter_supplier_contact_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_num',
            field=models.CharField(max_length=15),
        ),
    ]
