# Generated by Django 4.2.5 on 2023-10-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0003_alter_supplier_contact_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
