# Generated by Django 4.2.5 on 2023-10-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0003_purchaseheader_purchaseline_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_quantity',
        ),
    ]
