# Generated by Django 4.2.5 on 2023-10-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0003_purchaseheader_remove_item_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand_item',
        ),
    ]
