# Generated by Django 4.2.5 on 2023-10-12 10:41

import color_city_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0005_category_alter_item_catalyst_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(default=color_city_api.models.generate_product_number, max_length=20),
        ),
    ]
