# Generated by Django 4.2.5 on 2023-10-12 10:48

import color_city_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0006_alter_item_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(default=color_city_api.models.generate_product_number, max_length=20, unique=True),
        ),
    ]
