# Generated by Django 4.2.5 on 2023-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0006_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseheader',
            old_name='approval_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseheader',
            name='posted_status',
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseheader',
            name='received_status',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
