# Generated by Django 4.2.5 on 2023-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0007_alter_item_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='package',
            field=models.CharField(max_length=255),
        ),
    ]
