# Generated by Django 4.2.5 on 2023-10-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0008_purchaseheader_purchaser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseheader',
            name='purchaser_id',
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='color_city_api.supplier'),
        ),
    ]
