# Generated by Django 4.2.5 on 2023-10-10 14:11

import color_city_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
