# Generated by Django 4.2.5 on 2023-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0004_remove_item_brand_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='po_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
