# Generated by Django 4.2.5 on 2023-10-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color_city_api', '0005_purchaseheader_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='purchase_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color_city_api.purchaseheader'),
        ),
    ]
